{% set name = "tracktable" %}
{% set version = "1.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/sandialabs/tracktable
  git_rev: v1.7.2-bootstrap

build:
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake >=3.19.5
    - ninja  # [win]
    - make   # [unix]
  host:
    - python
    - setuptools
    - numpy
    - cartopy >=0.18.0
    - jupyter_core
    - nbconvert
    - pytz
    - shapely
    - tqdm
    - libboost-devel
    - libboost-python-devel
    - pip
  run:
    - python
    - setuptools
    - cartopy >=0.18.0
    - folium >=0.11.0
    - matplotlib-base
    - numpy
    - pyshp
    - pytz >=2020.1
    - shapely
    - six
    - tqdm
    - tracktable-data >=1.7.2

test:
  imports:
    - tracktable
    - tracktable.algorithms.dbscan
    - tracktable.algorithms.distance_geometry
    - tracktable.applications.assemble_trajectories
    - tracktable.applications.trajectory_splitter
    - tracktable.applications.prediction
    - tracktable.domain.rtree
    - tracktable.core.geomath
    - tracktable.domain.cartesian2d
    - tracktable.domain.cartesian3d
    - tracktable.domain.feature_vectors
    - tracktable.domain.terrestrial
    - tracktable.info.timezones
    - tracktable.render.render_trajectories

about:
  home: https://tracktable.sandia.gov/
  license_file: LICENSE.txt
  license: BSD-2-Clause
  license_url: https://opensource.org/licenses/BSD-2-Clause
  license_family: BSD
  summary: 'Trajectory Analysis and Rendering'
  description: >
    Tracktable is for analyzing trajectories from moving objects.  It
    provides modules to read in points/trajectories, assemble trajectories
    from points, compute features and feature vectors for trajectories,
    run DBSCAN clustering, search for similar trajectories, and render
    the results in static or dynamic maps.
  dev_url: https://github.com/sandialabs/tracktable
  doc_url: https://tracktable.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pabaxley
    - atwilso
